/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blender3D (https://sketchfab.com/Blender3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/0d62f4d3676545c88ec8523213c055dd
title: Minecraft Diamond Axe
*/

import {useFBX, useGLTF} from "@react-three/drei"
import axeUrl from "./assets/axe.glb"
import katanaUrl from "./assets/Wado_Ichimonji.fbx"
import {useEffect} from "react";

export default function Axe(props) {
  const { nodes, materials } = useGLTF(axeUrl)
    const fbx = useFBX(katanaUrl)
    useEffect(() => {
      console.log(fbx);
    }, []);

  return (
    <group dispose={null} {...props}>
      <group rotation={[0, 0, 0]} scale={0.03}>
          <primitive object={fbx} />
      </group>
    </group>
  )
}

useGLTF.preload(["/axe.glb"])
useFBX.preload("/Wado_Ichimonji.fbx")
